---
- hosts: all
  become: yes
  collections:
    - community.general

  pre_tasks:
    - name: Wait for SSH to be available
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 22
        delay: 5
        timeout: 100
        state: started
      delegate_to: localhost

  tasks:
    - name: Add Tailscale GPG key
      ansible.builtin.shell: |
        curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.noarmor.gpg \
          | tee /usr/share/keyrings/tailscale-archive-keyring.gpg > /dev/null
      args:
        creates: /usr/share/keyrings/tailscale-archive-keyring.gpg

    - name: Add Tailscale apt repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
        state: present

    - name: Install Tailscale
      ansible.builtin.apt:
        name: tailscale
        state: latest
        update_cache: yes

    - name: Start Tailscale
      ansible.builtin.command: tailscale up --authkey={{ tailscale_auth_key }} --hostname={{ inventory_hostname }}
      changed_when: false
